### ISSUE TITLE
your Web.config needs updating

### ISSUE THREAD

**Issue by aarongustafson** [Deraw-/whac-a-mole#2]
It is set to index.js and needs to be app.js I believe.

**Comment by deraw** [comment]
Oh yeah, right "Change index.js to your init script file" ! I did the change, sorry again

**Comment by molant** [comment]
@Deraw- also your app.js has some problems. You have a few lines starting with `.get` instead of `app`.

**Comment by deraw** [comment]
Yes, that something I've forgotten when pasted, it's fixed now !
